var searchData=
[
  ['scheduler_0',['Scheduler',['../group__nfc-scheduler.html',1,'']]],
  ['scopedlock_20functions_1',['ScopedLock functions',['../group__platform___scoped_lock.html',1,'']]],
  ['section_20function_2',['critical section function',['../group__platform__critical.html',1,'']]],
  ['section_20hal_20functions_3',['Critical Section HAL functions',['../group__hal__critical.html',1,'']]],
  ['secure_20element_20asymmetric_20cryptography_4',['Secure Element Asymmetric Cryptography',['../group__se__asymmetric.html',1,'']]],
  ['secure_20element_20authenticated_20encryption_20with_20additional_20data_5',['Secure Element Authenticated Encryption with Additional Data',['../group__se__aead.html',1,'']]],
  ['secure_20element_20driver_20initialization_6',['Secure element driver initialization',['../group__se__init.html',1,'']]],
  ['secure_20element_20driver_20registration_7',['Secure element driver registration',['../group__se__registration.html',1,'']]],
  ['secure_20element_20key_20derivation_20and_20agreement_8',['Secure Element Key Derivation and Agreement',['../group__driver__derivation.html',1,'']]],
  ['secure_20element_20key_20management_9',['Secure Element Key Management',['../group__se__key__management.html',1,'']]],
  ['secure_20element_20message_20authentication_20codes_10',['Secure Element Message Authentication Codes',['../group__se__mac.html',1,'']]],
  ['secure_20element_20symmetric_20ciphers_11',['Secure Element Symmetric Ciphers',['../group__se__cipher.html',1,'']]],
  ['security_20architecture_20psa_12',['Arm Platform Security Architecture (PSA)',['../group__experimental-crypto-psa.html',1,'']]],
  ['semaphore_20class_13',['Semaphore class',['../group__rtos___semaphore.html',1,'']]],
  ['serial_20configuration_20functions_14',['Serial Configuration Functions',['../group__hal___general_serial.html',1,'']]],
  ['serial_20hal_20tests_15',['Serial hal tests',['../group__hal___general_serial__tests.html',1,'']]],
  ['serial_20hardware_20abstraction_20layer_16',['Asynchronous Serial Hardware Abstraction Layer',['../group__hal___asynch_serial.html',1,'']]],
  ['serial_20rx_20events_20macros_17',['Serial RX Events Macros',['../group___serial_r_x_events.html',1,'']]],
  ['serial_20tx_20events_20macros_18',['Serial TX Events Macros',['../group___serial_t_x_events.html',1,'']]],
  ['serialbase_20class_19',['SerialBase class',['../group__drivers___serial_base.html',1,'']]],
  ['serialwireoutput_20class_20',['SerialWireOutput class',['../group__drivers___serial_wire_output.html',1,'']]],
  ['server_21',['Server',['../group__server.html',1,'']]],
  ['set_22',['AT/Hayes Command Set',['../group__at-hayes.html',1,'']]],
  ['sfdp_23',['SFDP',['../group__drivers-internal-api-sfdp.html',1,'']]],
  ['sha_201_24',['SHA-1',['../group__mbedtls__sha1__module.html',1,'']]],
  ['sha_20224_20and_20sha_20256_25',['SHA-224 and SHA-256',['../group__mbedtls__sha256__module.html',1,'']]],
  ['sha_20384_20and_20sha_20512_26',['SHA-384 and SHA-512',['../group__mbedtls__sha512__module.html',1,'']]],
  ['singletonptr_20class_27',['SingletonPtr class',['../group__platform___singleton_ptr.html',1,'']]],
  ['slave_28',['Synchronous I2C Hardware Abstraction Layer for slave',['../group___synch_i2_c.html',1,'']]],
  ['sleep_20hal_20requirements_29',['sleep hal requirements',['../group__hal__sleep.html',1,'']]],
  ['sleep_20hal_20tests_30',['sleep hal tests',['../group__hal__sleep__tests.html',1,'']]],
  ['sleep_20manager_20api_31',['Sleep manager API',['../group__hal__sleep__manager.html',1,'']]],
  ['sleep_20manager_20api_20tests_32',['Sleep manager API tests',['../group__hal__sleep__manager__tests.html',1,'']]],
  ['sockets_20abstraction_33',['Network Sockets Abstraction',['../group__mbedtls__net__module.html',1,'']]],
  ['span_20class_34',['Span class',['../group__platform___span.html',1,'']]],
  ['spi_35',['SPI',['../group__drivers-public-api-spi.html',1,'']]],
  ['spi_20class_36',['SPI class',['../group__drivers___s_p_i.html',1,'']]],
  ['spi_20configuration_20functions_37',['SPI Configuration Functions',['../group__hal___general_s_p_i.html',1,'']]],
  ['spi_20events_20macros_38',['SPI Events Macros',['../group__hal___s_p_i_events.html',1,'']]],
  ['spi_20hal_20tests_39',['SPI hal tests',['../group__hal___general_s_p_i__tests.html',1,'']]],
  ['spi_20hardware_20abstraction_20layer_40',['spi hardware abstraction layer',['../group___asynch_s_p_i.html',1,'Asynchronous SPI Hardware Abstraction Layer'],['../group___synch_s_p_i.html',1,'Synchronous SPI Hardware Abstraction Layer']]],
  ['spislave_20class_41',['SPISlave class',['../group__drivers___s_p_i_slave.html',1,'']]],
  ['ssl_20tls_42',['SSL/TLS',['../group__mbedtls__ssl__module.html',1,'']]],
  ['stats_20functions_43',['stats functions',['../group__platform__stats.html',1,'']]],
  ['storage_44',['Storage',['../group__storage.html',1,'']]],
  ['stream_20class_45',['Stream class',['../group__platform___stream.html',1,'']]],
  ['symmetric_20ciphers_46',['symmetric ciphers',['../group__se__cipher.html',1,'Secure Element Symmetric Ciphers'],['../group__cipher.html',1,'Symmetric ciphers']]],
  ['synchronous_20i2c_20hardware_20abstraction_20layer_20for_20slave_47',['Synchronous I2C Hardware Abstraction Layer for slave',['../group___synch_i2_c.html',1,'']]],
  ['synchronous_20spi_20hardware_20abstraction_20layer_48',['Synchronous SPI Hardware Abstraction Layer',['../group___synch_s_p_i.html',1,'']]],
  ['systimer_20class_49',['SysTimer class',['../group__mbed___sys_timer.html',1,'']]]
];
