var searchData=
[
  ['hal_0',['hal',['../group__hal.html',1,'HAL'],['../group__hal__mpu.html',1,'MPU hal'],['../group__hal__qspi.html',1,'QSPI HAL'],['../group__hal__rtc.html',1,'RTC hal'],['../group__hal__ticker__shared.html',1,'Ticker Hal']]],
  ['hal_20api_1',['hal api',['../group__flash__hal.html',1,'Flash HAL API'],['../group__itm__hal.html',1,'Instrumented Trace Macrocell HAL API'],['../group__hal__reset__reason.html',1,'ResetReason HAL API'],['../group__hal__watchdog.html',1,'Watchdog HAL API']]],
  ['hal_20functions_2',['hal functions',['../group__hal__analogin.html',1,'Analogin hal functions'],['../group__hal__analogout.html',1,'Analogout hal functions'],['../group__hal__critical.html',1,'Critical Section HAL functions'],['../group__hal__gpio.html',1,'GPIO HAL functions'],['../group__hal__gpioirq.html',1,'GPIO IRQ HAL functions'],['../group__hal__port.html',1,'Port HAL functions'],['../group__hal__pwmout.html',1,'Pwmout hal functions'],['../group__hal__ticker.html',1,'Ticker HAL functions'],['../group__hal__trng.html',1,'TRNG hal functions']]],
  ['hal_20requirements_3',['sleep hal requirements',['../group__hal__sleep.html',1,'']]],
  ['hal_20tests_4',['hal tests',['../group__hal__crc__tests.html',1,'crc hal tests'],['../group__hal__gpio__tests.html',1,'GPIO HAL tests'],['../group__hal__gpioirq__tests.html',1,'GPIO IRQ HAL tests'],['../group__hal__pwmout__tests.html',1,'GPIO IRQ HAL tests'],['../group__hal___general_i2_c__tests.html',1,'I2C hal tests'],['../group__hal__mpu__tests.html',1,'MPU hal tests'],['../group__hal__reset__reason__tests.html',1,'ResetReason HAL tests'],['../group__hal__rtc__tests.html',1,'RTC hal tests'],['../group__hal___general_serial__tests.html',1,'Serial hal tests'],['../group__hal__sleep__tests.html',1,'sleep hal tests'],['../group__hal___general_s_p_i__tests.html',1,'SPI hal tests'],['../group__hal__watchdog__tests.html',1,'Watchdog HAL tests']]],
  ['hardware_20abstraction_20layer_5',['hardware abstraction layer',['../group__hal___asynch_i2_c.html',1,'Asynchronous I2C Hardware Abstraction Layer'],['../group__hal___asynch_serial.html',1,'Asynchronous Serial Hardware Abstraction Layer'],['../group___asynch_s_p_i.html',1,'Asynchronous SPI Hardware Abstraction Layer'],['../group___synch_s_p_i.html',1,'Synchronous SPI Hardware Abstraction Layer']]],
  ['hardware_20abstraction_20layer_20for_20slave_6',['Synchronous I2C Hardware Abstraction Layer for slave',['../group___synch_i2_c.html',1,'']]],
  ['hardware_20accelerated_20asymmetric_20cryptography_7',['Hardware-Accelerated Asymmetric Cryptography',['../group__accel__asymmetric.html',1,'']]],
  ['hardware_20accelerated_20authenticated_20encryption_20with_20additional_20data_8',['Hardware-Accelerated Authenticated Encryption with Additional Data',['../group__accel__aead.html',1,'']]],
  ['hardware_20accelerated_20block_20ciphers_9',['Hardware-Accelerated Block Ciphers',['../group__accel__cipher.html',1,'']]],
  ['hardware_20accelerated_20message_20authentication_20code_10',['Hardware-Accelerated Message Authentication Code',['../group__accel__mac.html',1,'']]],
  ['hardware_20accelerated_20message_20digests_11',['Hardware-Accelerated Message Digests',['../group__driver__digest.html',1,'']]],
  ['hardware_20crc_12',['Hardware CRC',['../group__hal__crc.html',1,'']]],
  ['havege_13',['HAVEGE',['../group__mbedtls__havege__module.html',1,'']]],
  ['hayes_20command_20set_14',['AT/Hayes Command Set',['../group__at-hayes.html',1,'']]],
  ['hellman_15',['Elliptic Curve Diffie-Hellman',['../group__mbedtls__ecdh__module.html',1,'']]],
  ['hellman_20merkle_16',['Diffie-Hellman-Merkle',['../group__mbedtls__dhm__module.html',1,'']]],
  ['helper_20functions_17',['TLS helper functions',['../group__psa__tls__helpers.html',1,'']]],
  ['highresclock_20class_18',['HighResClock class',['../group__drivers___high_res_clock.html',1,'']]],
  ['hkdf_19',['HKDF',['../group__mbedtls__hkdf__module.html',1,'']]],
  ['hmac_5fdrbg_20',['HMAC_DRBG',['../group__mbedtls__hrmac__drbg__module.html',1,'']]],
  ['hook_20function_21',['Idle hook function',['../group__rtos___idle.html',1,'']]],
  ['hook_20functions_22',['RTOS hook functions',['../group__rtos__handlers.html',1,'']]]
];
