var searchData=
[
  ['file_0',['File',['../group__platform-public-api-file.html',1,'']]],
  ['filebase_20class_1',['FileBase class',['../group__platform___file_base.html',1,'']]],
  ['filehandle_20functions_2',['FileHandle functions',['../group__platform___file_handle.html',1,'']]],
  ['filelike_20class_3',['FileLike class',['../group__platform___file_like.html',1,'']]],
  ['filepath_20class_4',['FilePath class',['../group__platform___file_path.html',1,'']]],
  ['filesystem_5',['Filesystem',['../group__filesystem.html',1,'']]],
  ['filesystemhandle_20functions_6',['FileSystemHandle functions',['../group__platform___file_system_handle.html',1,'']]],
  ['filesystemlike_20functions_7',['FileSystemLike functions',['../group__platform___file_system_like.html',1,'']]],
  ['flash_20hal_20api_8',['Flash HAL API',['../group__flash__hal.html',1,'']]],
  ['flashiap_20class_9',['FlashIAP class',['../group__drivers___flash_i_a_p.html',1,'']]],
  ['for_20slave_10',['Synchronous I2C Hardware Abstraction Layer for slave',['../group___synch_i2_c.html',1,'']]],
  ['function_11',['function',['../group__platform__critical.html',1,'critical section function'],['../group__rtos___idle.html',1,'Idle hook function']]],
  ['functions_12',['functions',['../group__hal__analogin.html',1,'Analogin hal functions'],['../group__hal__analogout.html',1,'Analogout hal functions'],['../group__platform__atomic.html',1,'atomic functions'],['../group__platform___circular_buffer.html',1,'CircularBuffer functions'],['../group__hal__critical.html',1,'Critical Section HAL functions'],['../group__platform___critical_section_lock.html',1,'CriticalSectionLock functions'],['../group__platform__debug.html',1,'Debug functions'],['../group__platform___deep_sleep_lock.html',1,'DeepSleepLock functions'],['../group__platform___dir_handle.html',1,'DirHandle functions'],['../group__platform__error.html',1,'Error functions'],['../group__platform___file_handle.html',1,'FileHandle functions'],['../group__platform___file_system_handle.html',1,'FileSystemHandle functions'],['../group__platform___file_system_like.html',1,'FileSystemLike functions'],['../group__hal__gpio.html',1,'GPIO HAL functions'],['../group__hal__gpioirq.html',1,'GPIO IRQ HAL functions'],['../group__hal___general_i2_c.html',1,'I2C Configuration Functions'],['../group__platform___local_file_system.html',1,'LocalFileSystem functions'],['../group__platform__mem__trace.html',1,'mem_trace functions'],['../group__platform__mktime.html',1,'mktime functions'],['../group__platform__mpu__mgmt.html',1,'MPU management functions'],['../group__platform__interface.html',1,'Network interface and other utility functions'],['../group__platform__poll.html',1,'poll functions'],['../group__hal__port.html',1,'Port HAL functions'],['../group__platform__power__mgmt.html',1,'Power management functions'],['../group__hal__pwmout.html',1,'Pwmout hal functions'],['../group__platform__retarget.html',1,'Retarget functions'],['../group__platform__rtc__time.html',1,'rtc_time functions'],['../group__rtos__handlers.html',1,'RTOS hook functions'],['../group__platform___scoped_lock.html',1,'ScopedLock functions'],['../group__hal___general_serial.html',1,'Serial Configuration Functions'],['../group__hal___general_s_p_i.html',1,'SPI Configuration Functions'],['../group__platform__stats.html',1,'stats functions'],['../group__hal__ticker.html',1,'Ticker HAL functions'],['../group__psa__tls__helpers.html',1,'TLS helper functions'],['../group__platform__toolchain.html',1,'Toolchain functions'],['../group__hal__trng.html',1,'TRNG hal functions'],['../group__platform__wait__api.html',1,'wait_api functions']]]
];
