/* mbed Microcontroller Library
*******************************************************************************
* Copyright (c) 2018, STMicroelectronics
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
* 1. Redistributions of source code must retain the above copyright notice,
*    this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice,
*    this list of conditions and the following disclaimer in the documentation
*    and/or other materials provided with the distribution.
* 3. Neither the name of STMicroelectronics nor the names of its contributors
*    may be used to endorse or promote products derived from this software
*    without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
* FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*******************************************************************************
*/

#ifndef XSPI_COMAPT_H
#define XSPI_COMAPT_H

// XSPI compatibility layer: emulate XSPI API as OSPI API

#if defined(HAL_XSPI_MODULE_ENABLED) && !defined(TARGET_STM32U5)

// Types
#define OSPI_HandleTypeDef XSPI_HandleTypeDef
#define OSPI_RegularCmdTypeDef XSPI_RegularCmdTypeDef

// Members
#define ChipSelectHighTime ChipSelectHighTimeCycle
#define FifoThreshold FifoThresholdByte
#define DeviceSize MemorySize
#define InstructionSize InstructionWidth
#define AddressSize AddressWidth
#define AlternateBytesSize AlternateBytesWidth
#define NbData DataLength
#define InstructionDtrMode InstructionDTRMode
#define DataDtrMode DataDTRMode
#define AddressDtrMode AddressDTRMode
#define AlternateBytesDtrMode AlternateBytesDTRMode

// Enumeration Values
#define HAL_OSPI_ALTERNATE_BYTES_NONE HAL_XSPI_ALT_BYTES_NONE
#define HAL_OSPI_ALTERNATE_BYTES_8_BITS HAL_XSPI_ALT_BYTES_8_BITS
#define HAL_OSPI_ALTERNATE_BYTES_16_BITS HAL_XSPI_ALT_BYTES_16_BITS
#define HAL_OSPI_ALTERNATE_BYTES_24_BITS HAL_XSPI_ALT_BYTES_24_BITS
#define HAL_OSPI_ALTERNATE_BYTES_32_BITS HAL_XSPI_ALT_BYTES_32_BITS
#define HAL_OSPI_ALTERNATE_BYTES_1_LINE HAL_XSPI_ALT_BYTES_1_LINE
#define HAL_OSPI_ALTERNATE_BYTES_2_LINES HAL_XSPI_ALT_BYTES_2_LINES
#define HAL_OSPI_ALTERNATE_BYTES_4_LINES HAL_XSPI_ALT_BYTES_4_LINES
#define HAL_OSPI_ALTERNATE_BYTES_8_LINES HAL_XSPI_ALT_BYTES_8_LINES
#define HAL_OSPI_STATE_ERROR HAL_XSPI_STATE_ERROR
#define HAL_OSPI_STATE_RESET HAL_XSPI_STATE_RESET
#define HAL_OSPI_STATE_BUSY_TX HAL_XSPI_STATE_BUSY_TX
#define HAL_OSPI_STATE_BUSY_RX HAL_XSPI_STATE_BUSY_RX
#define HAL_OSPI_STATE_READY HAL_XSPI_STATE_READY
#define HAL_OSPI_TIMEOUT_DEFAULT_VALUE HAL_XSPI_TIMEOUT_DEFAULT_VALUE
#define HAL_OSPI_INSTRUCTION_NONE HAL_XSPI_INSTRUCTION_NONE
#define HAL_OSPI_INSTRUCTION_1_LINE HAL_XSPI_INSTRUCTION_1_LINE
#define HAL_OSPI_INSTRUCTION_2_LINES HAL_XSPI_INSTRUCTION_2_LINES
#define HAL_OSPI_INSTRUCTION_4_LINES HAL_XSPI_INSTRUCTION_4_LINES
#define HAL_OSPI_INSTRUCTION_8_LINES HAL_XSPI_INSTRUCTION_8_LINES
#define HAL_OSPI_DATA_NONE HAL_XSPI_DATA_NONE
#define HAL_OSPI_DATA_1_LINE HAL_XSPI_DATA_1_LINE
#define HAL_OSPI_DATA_2_LINES HAL_XSPI_DATA_2_LINES
#define HAL_OSPI_DATA_4_LINES HAL_XSPI_DATA_4_LINES
#define HAL_OSPI_DATA_8_LINES HAL_XSPI_DATA_8_LINES
#define HAL_OSPI_INSTRUCTION_8_BITS HAL_XSPI_INSTRUCTION_8_BITS
#define HAL_OSPI_INSTRUCTION_16_BITS HAL_XSPI_INSTRUCTION_16_BITS
#define HAL_OSPI_INSTRUCTION_DTR_ENABLE HAL_XSPI_INSTRUCTION_DTR_ENABLE
#define HAL_OSPI_INSTRUCTION_DTR_DISABLE HAL_XSPI_INSTRUCTION_DTR_DISABLE
#define HAL_OSPI_SIOO_INST_EVERY_CMD HAL_XSPI_SIOO_INST_EVERY_CMD
#define HAL_OSPI_DATA_DTR_ENABLE HAL_XSPI_DATA_DTR_ENABLE
#define HAL_OSPI_DATA_DTR_DISABLE HAL_XSPI_DATA_DTR_DISABLE
#define HAL_OSPI_ADDRESS_DTR_ENABLE HAL_XSPI_ADDRESS_DTR_ENABLE
#define HAL_OSPI_ADDRESS_DTR_DISABLE HAL_XSPI_ADDRESS_DTR_DISABLE
#define HAL_OSPI_ALTERNATE_BYTES_DTR_ENABLE HAL_XSPI_ALT_BYTES_DTR_ENABLE
#define HAL_OSPI_ALTERNATE_BYTES_DTR_DISABLE HAL_XSPI_ALT_BYTES_DTR_DISABLE
#define HAL_OSPI_DQS_ENABLE HAL_XSPI_DQS_ENABLE
#define HAL_OSPI_DQS_DISABLE HAL_XSPI_DQS_DISABLE
#define HAL_OSPI_OPTYPE_COMMON_CFG HAL_XSPI_OPTYPE_COMMON_CFG
#define HAL_OSPI_ADDRESS_NONE HAL_XSPI_ADDRESS_NONE
#define HAL_OSPI_FREERUNCLK_ENABLE HAL_XSPI_FREERUNCLK_ENABLE
#define HAL_OSPI_FREERUNCLK_DISABLE HAL_XSPI_FREERUNCLK_DISABLE
#define HAL_OSPI_ADDRESS_1_LINE HAL_XSPI_ADDRESS_1_LINE
#define HAL_OSPI_ADDRESS_2_LINES HAL_XSPI_ADDRESS_2_LINES
#define HAL_OSPI_ADDRESS_4_LINES HAL_XSPI_ADDRESS_4_LINES
#define HAL_OSPI_ADDRESS_8_LINES HAL_XSPI_ADDRESS_8_LINES
#define HAL_OSPI_ADDRESS_8_BITS HAL_XSPI_ADDRESS_8_BITS
#define HAL_OSPI_ADDRESS_16_BITS HAL_XSPI_ADDRESS_16_BITS
#define HAL_OSPI_ADDRESS_24_BITS HAL_XSPI_ADDRESS_24_BITS
#define HAL_OSPI_ADDRESS_32_BITS HAL_XSPI_ADDRESS_32_BITS
#define HAL_OSPI_MEMTYPE_MACRONIX HAL_XSPI_MEMTYPE_MACRONIX
#define HAL_OSPI_MEMTYPE_MICRON HAL_XSPI_MEMTYPE_MICRON
#define HAL_OSPI_MEMTYPE_APMEM HAL_XSPI_MEMTYPE_APMEM
#define HAL_OSPI_SAMPLE_SHIFTING_NONE HAL_XSPI_SAMPLE_SHIFT_NONE
#define HAL_OSPI_CLOCK_MODE_0 HAL_XSPI_CLOCK_MODE_0
#define HAL_OSPI_CLOCK_MODE_3 HAL_XSPI_CLOCK_MODE_3
#define HAL_OSPI_DHQC_ENABLE HAL_XSPI_DHQC_ENABLE
#define HAL_OSPI_DHQC_DISABLE HAL_XSPI_DHQC_DISABLE

// API Functions
#define HAL_OSPI_Init HAL_XSPI_Init
#define HAL_OSPI_DeInit HAL_XSPI_DeInit
#define HAL_OSPI_Command HAL_XSPI_Command
#define HAL_OSPI_Transmit HAL_XSPI_Transmit
#define HAL_OSPI_Receive HAL_XSPI_Receive
#define HAL_OSPI_Transmit_DMA HAL_XSPI_Transmit_DMA
#define HAL_OSPI_Receive_DMA HAL_XSPI_Receive_DMA
#define HAL_OSPI_IRQHandler HAL_XSPI_IRQHandler

// Callback Functions
#define HAL_OSPI_ErrorCallback HAL_XSPI_ErrorCallback
#define HAL_OSPI_AbortCpltCallback HAL_XSPI_AbortCpltCallback
#define HAL_OSPI_FifoThresholdCallback HAL_XSPI_FifoThresholdCallback
#define HAL_OSPI_CmdCpltCallback HAL_XSPI_CmdCpltCallback
#define HAL_OSPI_RxCpltCallback HAL_XSPI_RxCpltCallback
#define HAL_OSPI_TxCpltCallback HAL_XSPI_TxCpltCallback
#define HAL_OSPI_RxHalfCpltCallback HAL_XSPI_RxHalfCpltCallback
#define HAL_OSPI_TxHalfCpltCallback HAL_XSPI_TxHalfCpltCallback
#define HAL_OSPI_StatusMatchCallback HAL_XSPI_StatusMatchCallback
#define HAL_OSPI_TimeOutCallback HAL_XSPI_TimeOutCallback
#define HAL_OSPI_WRAP_NOT_SUPPORTED HAL_XSPI_WRAP_NOT_SUPPORTED
#define HAL_OSPI_DELAY_BLOCK_USED HAL_XSPI_DELAY_BLOCK_ON
#define HAL_OSPI_DELAY_BLOCK_BYPASS HAL_OSPI_DELAY_BLOCK_BYPASSED

#endif

#endif
